### ISSUE TITLE
UI issues adding new Account

### ISSUE THREAD

**Issue by ghost** [schott12521/PocketNanoWebsite#1]
Dialog box is cut off.
Cancel button is disabled.
Generic android loading animation used (intended for this box?)
Device: Samsung Galaxy S8

![screenshot_20180701-080417_pocket nano](https://user-images.githubusercontent.com/38169527/42135299-60fa5e88-7d06-11e8-8e41-08ebe0ac2253.jpg)

**Comment by slanos** [comment]
Should be resolved in the next build going out to testers!
