### ISSUE TITLE
UI Bug in Send window

### ISSUE THREAD

**Issue by ghost** [schott12521/PocketNanoWebsite#2]
When bringing up the list of accounts and tapping on it, the list is duplicated on each tap.

![20180701_081807](https://user-images.githubusercontent.com/38169527/42135381-887c7116-7d07-11e8-8817-ea9bf9cf7780.jpg)

Like this:

![screenshot_20180701-081610_pocket nano](https://user-images.githubusercontent.com/38169527/42135383-932ed6c6-7d07-11e8-83dd-7133e6935a82.jpg)

**Comment by slanos** [comment]
Changed this when I added the card, should be better now
